/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(remove_prefix_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c6ae06d2026a7803559b08707bdb3cef)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gfdm/remove_prefix_cc.h>
// pydoc.h is automatically generated in the build directory
#include <remove_prefix_cc_pydoc.h>

void bind_remove_prefix_cc(py::module& m)
{

    using remove_prefix_cc = ::gr::gfdm::remove_prefix_cc;


    py::class_<remove_prefix_cc,
               gr::block,
               gr::basic_block,
               std::shared_ptr<remove_prefix_cc>>(
        m, "remove_prefix_cc", D(remove_prefix_cc))

        .def(py::init(&remove_prefix_cc::make),
             py::arg("frame_len"),
             py::arg("block_len"),
             py::arg("offset"),
             py::arg("gfdm_sync_tag_key"),
             D(remove_prefix_cc, make))


        ;
}
