/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(resource_mapper_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(217e9baac003670d40f6cb69d6f1f23d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gfdm/resource_mapper_cc.h>
// pydoc.h is automatically generated in the build directory
#include <resource_mapper_cc_pydoc.h>

void bind_resource_mapper_cc(py::module& m)
{

    using resource_mapper_cc = ::gr::gfdm::resource_mapper_cc;


    py::class_<resource_mapper_cc,
               gr::block,
               gr::basic_block,
               std::shared_ptr<resource_mapper_cc>>(
        m, "resource_mapper_cc", D(resource_mapper_cc))

        .def(py::init(&resource_mapper_cc::make),
             py::arg("timeslots"),
             py::arg("subcarriers"),
             py::arg("active_subcarriers"),
             py::arg("subcarrier_map"),
             py::arg("per_timeslot"),
             D(resource_mapper_cc, make))


        ;
}
