/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(simple_receiver_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e504c62de6bc7e1a98560aed377d2cd5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gfdm/simple_receiver_cc.h>
// pydoc.h is automatically generated in the build directory
#include <simple_receiver_cc_pydoc.h>

void bind_simple_receiver_cc(py::module& m)
{

    using simple_receiver_cc = ::gr::gfdm::simple_receiver_cc;


    py::class_<simple_receiver_cc,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<simple_receiver_cc>>(
        m, "simple_receiver_cc", D(simple_receiver_cc))

        .def(py::init(&simple_receiver_cc::make),
             py::arg("n_timeslots"),
             py::arg("n_subcarriers"),
             py::arg("overlap"),
             py::arg("frequency_taps"),
             D(simple_receiver_cc, make))


        ;
}
