/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(transmitter_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(20483d83cf9e9306a359b915651bc41c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gfdm/transmitter_cc.h>
// pydoc.h is automatically generated in the build directory
#include <transmitter_cc_pydoc.h>

void bind_transmitter_cc(py::module& m)
{

    using transmitter_cc = ::gr::gfdm::transmitter_cc;


    py::class_<transmitter_cc,
               gr::block,
               gr::basic_block,
               std::shared_ptr<transmitter_cc>>(m, "transmitter_cc", D(transmitter_cc))

        .def(py::init(&transmitter_cc::make),
             py::arg("timeslots"),
             py::arg("subcarriers"),
             py::arg("active_subcarriers"),
             py::arg("cp_len"),
             py::arg("cs_len"),
             py::arg("ramp_len"),
             py::arg("subcarrier_map"),
             py::arg("per_timeslot"),
             py::arg("overlap"),
             py::arg("frequency_taps"),
             py::arg("window_taps"),
             py::arg("cyclic_shifts"),
             py::arg("preambles"),
             py::arg("tsb_tag_key") = "",
             D(transmitter_cc, make))


        ;
}
